### ISSUE TITLE
Bad IL Format.

### ISSUE THREAD

**Issue by axelriet** [neuecc/ZeroFormatter#129]
Hi,

I'm hitting an exception during Serialize in .NET 5.0 on Windows running the sample code from the intro page on this repo. Any idea?

System.BadImageFormatException
  HResult=0x8007000B
  Message=Bad IL format.
  Source=ZeroFormatter.DynamicObjectSegments
  StackTrace:
   at ZeroFormatter.DynamicObjectSegments.ZeroFormatter_Formatters_DefaultResolver.Program.MyClass$Formatter.Serialize(Byte[]& , Int32 , MyClass )
   at ZeroFormatter.ZeroFormatterSerializer.CustomSerializer`1.Serialize[T](Byte[]& buffer, Int32 offset, T obj)
   at ZeroFormatter.ZeroFormatterSerializer.CustomSerializer`1.Serialize[T](T obj)
   at ZeroFormatter.ZeroFormatterSerializer.Serialize[T](T obj)
   at Program.Main(String[] args) in Program.cs:line 62

**Comment by SeymourRu** [comment]
Due to some .Net internal optimisations, ZeroFormatter will no longer work on 3.0,3.1, 5.0, etc.
Now you have multiple options:
- Switch to other library (i.e [MessagePack ](https://github.com/neuecc/MessagePack-CSharp) from same author)
- Find fixed fork of ZeroFormatter and use library from there
- Fix it yourself

Decide what is more suitable to you and do it :)
