### ISSUE TITLE
Exception when deserializing self-referencing struct/class

### ISSUE THREAD

**Issue by jdehlin** [neuecc/ZeroFormatter#63]
I have a struct which contains a property that is a list of that same struct type. When deserializing I get a null reference exception. I've tried converting it to a class, using fields rather than properties, List rather than IList, and making the getter return a new List if the backing field is null.

```
    [ZeroFormattable]
    public struct AllTimeBest
    {
        [Index(0)]
        public float Seconds { get; set; }

        [Index(1)]
        public IList<AllTimeBest> History { get; set; }

        public AllTimeBest(float seconds, IList<AllTimeBest> history)
        {
            Seconds = seconds;
            History = history ?? new List<AllTimeBest>();
        }
    }
```

```
Test method PersonalRecords.Test.SerializationTests.AllTimeBestsZero threw exception: 
System.NullReferenceException: Object reference not set to an instance of an object.

    at ZeroFormatter.Formatters.ListFormatter`2.Serialize(Byte[]& bytes, Int32 offset, IList`1 value)
   at ZeroFormatter.DynamicObjectSegments.ZeroFormatter_Formatters_DefaultResolver.PersonalRecords.Models.AllTimeBest$Formatter.Serialize(Byte[]& , Int32 , AllTimeBest )
   at ZeroFormatter.Formatters.InterfaceEnumerableFormatter`2.Serialize(Byte[]& bytes, Int32 offset, IEnumerable`1 value)
   at ZeroFormatter.ZeroFormatterSerializer.CustomSerializer`1.Serialize[T](Byte[]& buffer, Int32 offset, T obj)
   at ZeroFormatter.ZeroFormatterSerializer.CustomSerializer`1.Serialize[T](T obj)
   at ZeroFormatter.ZeroFormatterSerializer.Serialize[T](T obj)
   at PersonalRecords.Services.PersonalRecordService.SerializeDeserializeZero(Int32 memberId, Guid seasonGuid) in C:\Users\jdehlin\Projects\TrainerRoadPersonalRecords\projects\PersonalRecords\Services\PersonalRecordService.cs:line 136
   at PersonalRecords.Test.SerializationTests.AllTimeBestsZero() in C:\Users\jdehlin\Projects\TrainerRoadPersonalRecords\projects\PersonalRecords.Test\SerializationTests.cs:line 25
```

**Comment by neuecc** [comment]
Currently ZeroFormatter can not serialize types that contain the same type as itself.
This is a cheap implementation to prevent Stackoverflow.
However, it is not good.
The exception message is also unkind.

I'll fix it, thank you.

**Comment by grendo** [comment]
Any ETA when this would be available or the code the is require as it is a blocking issue for me.

In the short term I will just swap to protobufs-net as it works for this situation.

**Comment by rmindel** [comment]
Waiting for the resolution of this issue too, switching to protobufs-net also :)

**Comment by aliarbak** [comment]
Is there any update about this issue? @neuecc do you have any suggestion to prevent this situation?

**Comment by ramanvivek** [comment]
HFr
