### ISSUE TITLE
zfc.exe Couldn't load file or assembly System.Collections.Immutable

### ISSUE THREAD

**Issue by ghost** [neuecc/ZeroFormatter#86]
I'm trying to generate the code for Unity using zfc, but getting an exception. Here is my command (zfc is under Assets/Scripts/Serialization) zfc.exe -i "../../../Assembly-CSharp.csproj" -o "ZeroFormatterGenerated.cs".

The exception is:
Unhandled Exception: System.IO.FileNotFoundException: Could not load file or assembly 'System.Collections.Immutable, Version=1.1.37.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.
   at ZeroFormatter.CodeGenerator.TypeCollector..ctor(String csProjPath, IEnumerable`1 conditinalSymbols, IEnumerable`1 allowCustomTypes, Boolean disallowInternal, Boolean generatePropertyTypeEnumOnly, Boolean disallowInMetadata, Boolean generateComparerKeyTypeEnumOnly, String namespaceRoot)
   at ZeroFormatter.CodeGenerator.Program.Main(String[] args)

**Comment by ghost** [comment]
This happens only on the latest version 1.6.4 at the moment. Seems like some unresolved dependency issue in the zfc. Using the zfc from 1.6.3 resolved the issue.
